"""multi db connection and schemas

Revision ID: df40ced5827c
Revises: 66da84fa3735
Create Date: 2026-05-14 14:26:44.066167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df40ced5827c'
down_revision: Union[str, Sequence[str], None] = '66da84fa3735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_db_credentials_clerk_user_id'), table_name='user_db_credentials')
    op.drop_table('user_db_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_db_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clerk_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('db_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('host', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('db_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_enc', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_db_credentials_pkey'))
    )
    op.create_index(op.f('ix_user_db_credentials_clerk_user_id'), 'user_db_credentials', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###
